#!/usr/local/bin/perl
use strict;
use warnings;
use CGI qw/:standard/;           # load standard CGI routines
use Bio::SeqIO;


my $seqio_obj = Bio::SeqIO->new(-file => "19.fa", -format => "fasta" );
my $seq_obj = $seqio_obj->next_seq;
my $len = $seq_obj->length;
my $part = $seq_obj->subseq(100000,100022);

print          header,                    # create the HTTP header
               start_html('hello world'), # start the HTML
               h1('Extracted fragment'),         # level 1 header
               p("$part, from $len bp"),                 # print the fragment 
               end_html;                  # end the HTML

