#!/usr/bin/perl

# $Id: wb_people,v 1.1.1.1 2010-01-25 15:36:03 tharris Exp $

use warnings;
use strict;

use CGI qw(:standard);

use ElegansSubs qw(:DEFAULT);
use WormBase::GMapView;
use Ace::Browser::AceSubs qw(:DEFAULT Configuration);

my $zoom_level = param('zoom_level') || 0;
my $base_sql_table = $zoom_level >= 13 ? 'wb_by_person2' : 'wb_by_person';

my $large = param('size') && param('size') eq 'large' ? 1 : 0;

my $db   = Configuration->Geo_map_db;
my $user = Configuration->Geo_map_user;
my $pass = Configuration->Geo_map_pass;

my $gmap = WormBase::GMapView->new (
    initial_format        => 'xml-hires',
    page_title            => 'WormBase People',
    header                => ElegansSubs::Banner() . ElegansSubs::Header(),
    footer                => ElegansSubs::Footer(),
    db_access_params      => ["DBI:mysql:database=$db;host=localhost;port=3306", $user,$pass],
    base_sql_table        => $base_sql_table,
    base_sql_fields       => ['id',
                              'person_id',
                              'name',
                              'address',
                              'institution',
                              'papers',
                              'papers_rounded',
                              'supervised',
                              'supervised_rounded',
                              'accuracy',
                              'latitude',
                              'longitude',
                              ],
    base_output_headers   => ['Id',
                              'Person Id',
                              'Name',
                              'Address',
                              'Institution',
                              'Publications',
                              'Publications',
                              'Supervised',
                              'Student/Mentor',
                              'Location Accuracy',
                              'Latitude',
                              'Longitude',
                              ],
    legend_field1         => 'supervised_rounded',
    legend_field2         => 'papers_rounded',
    param_fields          => {
      supervised_rounded => ['all:All', 'Student', 'Mentor'],
      papers_rounded     => ['all:All', 'no:none', '1-5', '5-25', '26-125', '> 126'],
    },
    gmap_key              => Configuration->Gmap_api_key,
    temp_dir              => qq[/usr/local/wormbase/html/geo_map/_tmp],
    temp_dir_eq           => qq[/geo_map/_tmp],
    request_url_template  => Configuration->Wormbase2blast . qq[/db/misc/wb_people?database=default;format=xml-hires],
    max_hires_display     => 600,
    hires_shape_keys      => ['Mentor', 'Student'],
    hires_shape_values    => ['square', 'diamond'],
    hires_color_keys      => ['No',      '1-5',     '5-25',    '6-25',    '26-125',  '> 126'],
    hires_color_values    => ['#ffff00', '#ffc000', '#ffa000', '#ff6000', '#ff4200', '#ff0000'],
    center_latitude       => 0,
    center_longitude      => $large ? 30 : 20,
    center_zoom           => 2,
    image_height_pix      => 600,
    image_width_pix       => $large ? 840 : 600,
    tile_height_pix       => 60,
    tile_width_pix        => 60,
);

# Display
$gmap->display;


=head1 NAME

html_gmap_hires_sample - Sample CGI script for HTML::GMap

=head1 SYNOPSIS

html_gmap_hires_sample

=head1 DESCRIPTION

Sample code for demonstrating use of HTML::GMap in hires mode.

=head1 USAGE

Please refer to HTML::GMap::Tutorial for details on this script.

=head1 AUTHOR

Payan Canaran <canaran@cshl.edu>

=head1 BUGS

=head1 VERSION

=head1 ACKNOWLEDGEMENTS

=head1 COPYRIGHT & LICENSE

Copyright (c) 2006-2007 Cold Spring Harbor Laboratory

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself. See DISCLAIMER.txt for
disclaimers of warranty.

=cut
