#!/usr/bin/perl

use strict;
use Bio::Das;
use Bio::Graphics::Panel;
#use Ace::Graphics::Panel;
use Ace::Browser::AceSubs qw/:DEFAULT/;
use CGI qw/:standard/;

my $map        = param('map');
my $comb       = param('comb');
my $url        = param('url');
my $dsn        = param('dsn');
my @feature    = param('feature');
my $start      = param('start');
my $end        = param('end');
my $refseq     = param('refseq');
   $refseq     = "Locus:$refseq" if $refseq =~ /^[a-z]{3}-\d+$/;
   $refseq     =~ s/^CHROMOSOME_// if $url =~ /www\.wormbase\.org/;
my $db         = Bio::Das->new($url=>$dsn) or die "Can't get DAS server";
# $db->debug(1);
my $style      = $db->stylesheet;
my $segment    = $db->segment(-refseq=>$refseq,-start=>$start,-stop=>$end);

@feature       = grep {defined $_} @feature; #clean up
#warn "fetching features";
my @features   = $segment->features(@feature); #note the 's'
#warn "got features";

#my %feature;
#foreach(@feature){$feature{lc($_)} = 1;}

#start the panel
#my $panel = Ace::Graphics::Panel->new(-segment=>$segment,-width=>600);
my $panel = Bio::Graphics::Panel->new(-segment=>$segment,-width=>800,-key_style=>'between');

#add a comb
$panel->add_track(arrow => $segment,-bump => 0,-tick=>2) if $comb == 1;

#make a hash of tracks to be shown;
my %track;
foreach my $f (@features){
  eval{$f->type} or next;
  my $type = lc( $f->type );

#  warn "feature = $f";

 # push @{$track{$type}},$f if $feature{$type};
  push @{$track{$type}},$f;
}
unless (%track || $comb) {  # no tracks, nothing to show
  print redirect('/images/no_das_data.gif');
  exit 0;
}

#now make the tracks;
foreach my $track (sort keys %track){

  my @lanes = @{$track{$track}};
  my ($glyph,@attributes) = eval {$style->glyph($track{$track}[0])};
#  warn "$track: $glyph => @attributes";

#  warn "track = $track";
#  warn "lanes = @lanes";
  $glyph ||= 'generic';
  push @attributes,-bump=>@lanes < 50 ? 1 : 0;
  $panel->add_track( $track{$track} =>$glyph,@attributes,-key=>$track) if @lanes;
}

if($map){
#  warn "calling boxes";
  my $boxes = $panel->boxes;
#  warn "done boxes";
  foreach (@$boxes){
    next if ref $_->[0] eq 'Bio::Das::Segment';
    my $alt  = $_->[0]->description || $_->[0];
    my $href = $_->[0]->link || '/das_missing.html';
    print qq(<AREA SHAPE="RECT" COORDS="$_->[1],$_->[2],$_->[3],$_->[4]" HREF="$href" ALT="$alt" TITLE="$alt">);
  }
} else {
#  warn "calling gd";
  my $gd = $panel->gd;
#  warn "gd done";
  if ($gd->can('gif')) {
    print header(-type=>'image/gif');
    print $gd->gif;
  } else {
    print header(-type=>'image/png');
    print $gd->png;
  }
#  print header(-type=>'image/gif');
#  print $panel->gif;
}
