#!/usr/bin/perl -w
# file: sequenceapplet
# launches jadex applet for displaying sequence maps

use strict;
use lib '../lib';
use vars qw($JARFILES $HOST $DB $ARCHIVE);
use vars qw($CHROMOSOME $NAME);

use CGI 2.42 ':standard';
use Ace::Browser::AceSubs;
use ElegansSubs;

# print HTTP header & open the database
$DB = OpenDatabase() || AceError("Couldn't open database.");

my $jadex_path = Configuration->Jadex_path;
my $pos = index($jadex_path, 'jadex.jar');
$jadex_path = substr($jadex_path, 0, $pos);
$HOST       = server_name();
my $port    = server_port;
$ARCHIVE    = "http://$HOST:${port}$jadex_path";
$JARFILES = $ARCHIVE . "jdom.jar, ". $ARCHIVE . "utilities.jar, ". $ARCHIVE .
"jadexSequence.jar";

#### Get the object name

my $obj = param("name");
$NAME = $obj;

  # find out what chromosome we're on
  if ($obj =~ /CHROMOSOME/i) { $CHROMOSOME = $obj; }
  elsif (my $sequence = $DB->fetch(Sequence=>$obj)) {
    my $parent;
    $parent = $sequence->Source;
    while (!($parent =~ /CHROMOSOME/i)) {
    	$parent = $parent->Source;
    }		
    $CHROMOSOME = $parent;
    }

PrintTop($NAME, "Sequence", "Interactive Sequence Viewer: $NAME"); 

my $agent = "HTTP_USER_AGENT";
my $user = $ENV{$agent};
#my $user = "Mozilla/4.73 [en] (X11; U; Linux 2.2.14-5.0smp i686";

if (($user =~ /MSIE/) && ($user =~ /Win/) && !($user =~ /Windows 3.1/)) {
  printIE();
}
elsif ($user =~ /Mozilla/) {
  if (($user =~ /Win/) && !($user =~ /Win16/)) { printNSWin();}
  elsif ($user =~ /Linux/) { printNSLinux(); }
  elsif ($user =~ /Sun/) { printNSSun(); }
}
else { printOthers(); }

PrintBottom();

exit 0;

##########################################################################

########### printIE

sub printIE {

  print <<END;

<OBJECT classid="clsid:8AD9C840-044E-11D1-B3E9-00805F499D93" WIDTH = 100%
HEIGHT = 650
codebase="http://java.sun.com/products/plugin/1.3/jinstall-13-win32.cab#Version=1,3,0,0">  
<PARAM NAME = CODE VALUE = jadex.swing.sequence.SequenceViewApplet> 
<PARAM NAME = CODEBASE VALUE = "$ARCHIVE">
<PARAM NAME = ARCHIVE VALUE = "jadexSequence.jar, jdom.jar, utilities.jar"> 
<PARAM NAME="type" VALUE="application/x-java-applet;version=1.3"> 
<PARAM NAME="scriptable" VALUE="false"> 
<PARAM NAME = "chromosome" VALUE ="$CHROMOSOME"> 
<PARAM NAME = "sequence" VALUE = "$NAME"> 
</OBJECT>
END
}

########## printNSWin

sub printNSWin {

  print
nsCommon()."pluginspage=\"http://java.sun.com/j2se/1.3/jre/download-windows.html\"></EMBED>";

 }


######## printNSLinux

sub printNSLinux {
 
  print
nsCommon()."pluginspage=\"http://java.sun.com/j2se/1.3/download-linux.html\"></EMBED>";

}

############ printNSSun

sub printNSSun {

  print
nsCommon()."pluginspage=\"http://java.sun.com/j2se/1.3/jre/download-solaris.html\"></EMBED>";

}

########## printOthers: all other OS

sub printOthers {
  print <<END;

  Sorry, try to find your <a href=http://java.sun.com/products/plugin/>Java
plug-in</a> by yourself.

END
}

########### nsCommon: the common code for netscape

sub nsCommon {
	
	my $ns = "<EMBED type=\"application/x-java-applet;version=1.3\" 
CODE = \"jadex.swing.sequence.SequenceViewApplet\" CODEBASE = \"$ARCHIVE\"
ARCHIVE =\"jadexSequence.jar, jdom.jar, utilities.jar\" WIDTH = 100% HEIGHT =
650 chromosome = \"$CHROMOSOME\"  sequence = \"$NAME\" scriptable=false ";

	return $ns;
}

####### END ##########################
