#!/usr/bin/perl

use lib '../lib';
use CGI qw(:standard);
use Tie::Hash;
use strict;
use Ace::Browser::AceSubs;
use ElegansSubs;

OpenDatabase();
PrintTop();

my @forms = (
             ['section', 'General'],
             ['New Large Scale Datasets'           , ['pws@caltech.edu'],['Paul Sternberg']],
             ['Addresses of Authors'               , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/person.cgi']],
             ['Wormbase User\'s Guide'             , ['wen@athena.caltech.edu'], ['Wen Chen']],
	     ['Updating contact information'       , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/person.cgi']],
	     ['Updating intellectual lineage information',['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/person_lineage.cgi']], 
	     ['User Interface Suggestions'         , ['harris@cshl.edu'],['Todd Harris']],
             ['Complaints and Suggestions'         , ['pws@caltech.edu'], ['Paul Sternberg']],

             ['section', 'Sequence and Gene Structure'],
             ['Physical Map'                       , ['help@wormbase.org'], ['WormBase Consortium']],
             ['Sequence/Gene Structures'           , ['worm@sanger.ac.uk'], ['Sequence Consortium']],
             ['Transcriptome Project'              , ['mieg@ncbi.nlm.nih.gov'], ['Jean Thierry-Mieg']],


             ['section', 'Proteome/WormPep'],
             ['Sequence Analysis'                  , ['rd@sanger.ac.uk'], ['Richard Durbin']],
	     ['Proteomics Data'                    , ['gw3@sanger.ac.uk'], ['Gary Williams']],
	     # ['New Polymorphism Data'              , ['http://www.sanger.ac.uk/Projects/C_elegans/CGC/Poly_form.shtml']],
             ['Gene/Sequence Links'                , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/gene_name.cgi']],

             ['section', 'Cells and Anatomy'],
             ['Anatomy'                            , ['raymond@caltech.edu'], ['Raymond Lee']],
             ['Cell Function'                      , ['raymond@caltech.edu'], ['Raymond Lee']],
             ['Pictures of Cells'                  , ['raymond@caltech.edu'], ['Raymond Lee']],
             ['Gene Expression and Regulation'     , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/expr_pattern.cgi']],
             ['Nomenclature'                       , ['wen@athena.caltech.edu'], ['Wen Chen']],


             ['section', 'Gene Function'],
             ['Gene Expression and Regulation'     , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/expr_pattern.cgi']],
             ['Gene Interaction'                   , ['emsch@its.caltech.edu'], ['Erich Schwarz']],
             ['RNAi'                               , ['http://elbrus.caltech.edu/cgi-bin/igor/rnaitools/rnai_submission']],
             ['Transgenes'                         , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/transgene.cgi']],
             ['Gene Ontology (GO) Terms'           , ['emsch@its.caltech.edu'], ['Erich Schwarz']],


             ['section', 'Genes'],
             ['Gene/Sequence Links'                , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/gene_name.cgi']],
             ['New/Altered Locus Data'             , ['help@wormbase.org'],['WormBase Curators']],
	      #['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/gene_name.cgi']],
#             ['New Polymorphism Data'              , ['http://www.sanger.ac.uk/Projects/C_elegans/CGC/Poly_form.shtml']],
             ['Transgenes'                         , ['wen@athena.caltech.edu'], ['Wen Chen']],
#             ['Sequence Alteration by a Mutation'  , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/gene_name.cgi']],


             ['section', 'Genetic Map Data'],
  	     ['Allele data'			   , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/allele.cgi']], 
             ['Breakpoint Data'                    , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/breakpoint.cgi']],
             ['Deletion/Duplication Data'          , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/df_dp.cgi']],
             ['Multipoint Cross Data'              , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/multi_pt.cgi']],
             ['Two-point Cross Data'               , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/2_pt_data.cgi']],
             ['New/Altered Locus Data'             , ['help@wormbase.org'],['WormBase Curators']],
  # ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/gene_name.cgi']],
             ['New/Altered Rearrangement Data'     , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/rearrangement.cgi']],
             ['SNP Map Data/Sequence/Verification' , ['worm@sanger.ac.uk'], ['Sequence Consortium']],
             ['Strains/CGC'                        , ['stier@biosci.cbs.umn.edu'], ['Theresa Stiernagle']],
             ['Gene/Sequence Links'                , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/gene_name.cgi']],

             ['section', 'Nomenclature'],
             ['CGC'                                , ['stier@biosci.cbs.umn.edu'], ['Theresa Stiernagle']],
             ['Gene Synonyms'                      , ['genenames@wormbase.org'], ['CGC']],
             ['New Gene Class Name Proposal'       , ['http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/gene_name.cgi']],
             ['Request New Laboratory Designation' , ['genenames@wormbase.org'], ['CGC']],
             ['Gene Ontology (GO) Terms'           , ['emsch@its.caltech.edu'], ['Erich Schwarz']],
             ['Cell Nomenclature'                  , ['wen@athena.caltech.edu'], ['Wen Chen']],
             ['Literature Citations'               , ['help@wormbase.org'], ['WormBase Consortium']],
            );

print p('WormBase welcomes data submissions!',
	'Please choose the online form or e-mail address that best matches the type of data you wish to submit.',
	'For general questions and comments, use the <a href="/db/misc/feedback">feedback page</a> or send e-mail directly to',
	a({-href=>'mailto:pws@its.caltech.edu'},'Paul Sternberg')
	);

print '<table class="resultsbody">';

my $in = 0;
foreach (@forms){
  if ($_->[0] eq 'section') {
      print '</table><br>';
                          print '<table width="100%" class="resultsbody">';
			  print "<tr><td colspan=2 class=\"resultstitle\"><b>$_->[1]</b></td></tr>";
			  $in = 1;
			  next;
			  }
  my $alink;

  print "<tr><td width='50%'>$_->[0]</td><td>";

  #it is a URL
  unless (@{$_->[1]}[0] =~ /\@/) { $alink = ('Fill out online form'); print a({-href=>@{$_->[1]}[0]},$alink);}
  #is is an Email address
  else {
        my $href = join ',', @{$_->[1]};
	   $alink = "Email ". join ", ", @{$_->[2]};

	print a({-href=>"mailto:$href?subject=Wormbase online form RE: $_->[0]"},$alink);
        }

  print '</td></tr>';
}
print '</table>';

PrintBottom();
