#!/usr/bin/perl -w
use lib '/usr/local/wormbase/website-classic/cgi-perl/karyotype/conf/gbrowse.conf/';

#$Id: moby_server.PLS,v 1.6.12.1 2008-09-12 14:32:35 scottcain Exp $
use SOAP::Transport::HTTP;
use MobyServices::GbrowseServices;
use strict;

my $x = new SOAP::Transport::HTTP::CGI;

$x->dispatch_with({
    'http://biomoby.org/#GbrowseGetReferenceSeqObj' =>  'MobyServices::GbrowseServices',
    'http://biomoby.org/#GbrowseGetReferenceFasta' =>  'MobyServices::GbrowseServices',
    'http://biomoby.org/#GbrowseGetReferenceGFF2' =>  'MobyServices::GbrowseServices',
    'http://biomoby.org/#GbrowseGetReferenceGFF3' =>  'MobyServices::GbrowseServices',
    'http://biomoby.org/#GbrowseGetFeatureSequenceObject' =>  'MobyServices::GbrowseServices',
    'http://biomoby.org/#GbrowseGetFeatureGFF3' =>  'MobyServices::GbrowseServices',
    'http://biomoby.org/#GbrowseGetFeatureGFF2' =>  'MobyServices::GbrowseServices',
    
    });
$x->handle;

